### ISSUE TITLE
Character Flip bug

### ISSUE THREAD

**Issue by Kuroboshi500** [WheeledParasite/Hack-N-Slash#60]
All current progress on character flip is on the Character_Flip branch

-When flipping(rotation based) the character to the left the health bar will be flipped out of the frame and the arms seem to stay attached to the mouse on the right side of the screen.

-When flipping(Scale based) the arms can only bend the elbow in a downwards motion and is overall slower, also the health bar is flipped as well 

-Double pressing needs more time between presses to work
    -Currently, the character can flip by just pressing the correct directional key without requiring a double press

**Comment by Kuroboshi500** [comment]
-Scale based flipping

It would appear that the hinge joints for both parts of the arms are not being flipped

**Comment by Kuroboshi500** [comment]
-Rotation based flipping

Seems like it doesn't function correctly and makes the arms invert(?) upon itself.

**Comment by gururise** [comment]
Couple of things I noticed that are causing you problems:

1. The GameObjects are being flipped correctly; however, when the arm is flipped (to the left), the **HINGE ANGLES** need to be adjusted so that the arm bends in the opposite direction.
2. Flipping should only occur on a "**double tap**" movement, but right now it flips whenever you move left or right.

I think those two issues are pretty minor.  @WheeledParasite can help you resolve them if you need additional help.
